(require 'init-sr-speedbar)
(require 'init-evil)
(require 'init-saves)
(require 'init-helper-functions)
(require 'init-keys)
(require 'init-smartparens)
(require 'init-custom)
(setq mouse-autoselect-window t)
(provide 'init-local)
