(require 'init-sr-speedbar)
(require 'init-evil)
(require 'init-saves)
;(require 'init-graphene-small)
(require 'init-helper-functions)
(require 'init-keys)
(require 'init-smartparens)
(require 'init-custom)

(provide 'init-local)
